USE ecommerce_analytics;

-- Count products in each category
SELECT
    category_id,
    COUNT(*) AS total_products
FROM products
GROUP BY category_id;

-- Calculate average product price by category
SELECT
    category_id,
    ROUND(AVG(price), 2) AS average_price
FROM products
GROUP BY category_id;

-- Calculate total stock by category
SELECT
    category_id,
    SUM(stock_quantity) AS total_stock
FROM products
GROUP BY category_id;

-- Find the highest priced product in each category
SELECT
    category_id,
    MAX(price) AS highest_price
FROM products
GROUP BY category_id;

-- Find the lowest priced product in each category
SELECT
    category_id,
    MIN(price) AS lowest_price
FROM products
GROUP BY category_id;

-- Count orders by status
SELECT
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;

-- Calculate order value by status
SELECT
    order_status,
    SUM(total_amount) AS total_value
FROM orders
GROUP BY order_status;

-- Calculate average order value by status
SELECT
    order_status,
    ROUND(AVG(total_amount), 2) AS average_order_value
FROM orders
GROUP BY order_status;

-- Count orders placed by each customer
SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id;

-- Calculate total spending by customer
SELECT
    customer_id,
    SUM(total_amount) AS total_spending
FROM orders
GROUP BY customer_id;

-- Find customers who have placed more than one order
SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- Find customers who spent more than 5000
SELECT
    customer_id,
    SUM(total_amount) AS total_spending
FROM orders
GROUP BY customer_id
HAVING SUM(total_amount) > 5000;

-- Calculate total sales by payment method
SELECT
    payment_method,
    SUM(amount) AS total_amount
FROM payments
GROUP BY payment_method;

-- Count payments by payment status
SELECT
    payment_status,
    COUNT(*) AS total_payments
FROM payments
GROUP BY payment_status;

-- Calculate average product rating
SELECT
    product_id,
    ROUND(AVG(rating), 2) AS average_rating
FROM reviews
GROUP BY product_id;

-- Count reviews for each product
SELECT
    product_id,
    COUNT(*) AS total_reviews
FROM reviews
GROUP BY product_id;

-- Find products with an average rating of at least four
SELECT
    product_id,
    ROUND(AVG(rating), 2) AS average_rating
FROM reviews
GROUP BY product_id
HAVING AVG(rating) >= 4;

-- Calculate total quantity sold for each product
SELECT
    product_id,
    SUM(quantity) AS total_quantity_sold
FROM order_items
GROUP BY product_id;

-- Calculate total revenue generated by each product
SELECT
    product_id,
    SUM(quantity * unit_price - discount_amount) AS total_revenue
FROM order_items
GROUP BY product_id;

-- Find products with more than five units sold
SELECT
    product_id,
    SUM(quantity) AS total_quantity_sold
FROM order_items
GROUP BY product_id
HAVING SUM(quantity) > 5;

-- Group orders by year
SELECT
    YEAR(order_date) AS order_year,
    COUNT(*) AS total_orders
FROM orders
GROUP BY YEAR(order_date);

-- Calculate yearly revenue
SELECT
    YEAR(order_date) AS order_year,
    SUM(total_amount) AS total_revenue
FROM orders
GROUP BY YEAR(order_date);

-- Group orders by month
SELECT
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date);

-- Calculate monthly revenue
SELECT
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    SUM(total_amount) AS monthly_revenue
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY order_year, order_month;

-- Find categories with more than two products
SELECT
    category_id,
    COUNT(*) AS total_products
FROM products
GROUP BY category_id
HAVING COUNT(*) > 2;

-- Find sellers with products worth more than 10000
SELECT
    seller_id,
    SUM(price * stock_quantity) AS inventory_value
FROM products
GROUP BY seller_id
HAVING SUM(price * stock_quantity) > 10000;