USE ecommerce_analytics;

-- Match each product with its category
SELECT
    p.product_id,
    p.product_name,
    c.category_name,
    p.price
FROM products p
INNER JOIN categories c
    ON p.category_id = c.category_id;

-- Match each product with its seller
SELECT
    p.product_id,
    p.product_name,
    s.seller_name,
    p.price
FROM products p
INNER JOIN sellers s
    ON p.seller_id = s.seller_id;

-- Display customers and their orders
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.total_amount
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id;

-- Display all customers including customers without orders
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.total_amount
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id;

-- Display all categories including categories without products
SELECT
    c.category_id,
    c.category_name,
    p.product_id,
    p.product_name
FROM categories c
LEFT JOIN products p
    ON c.category_id = p.category_id;

-- Display all sellers including sellers without products
SELECT
    s.seller_id,
    s.seller_name,
    p.product_id,
    p.product_name
FROM sellers s
LEFT JOIN products p
    ON s.seller_id = p.seller_id;

-- Match orders with payment details
SELECT
    o.order_id,
    o.order_date,
    o.total_amount,
    p.payment_method,
    p.payment_status
FROM orders o
INNER JOIN payments p
    ON o.order_id = p.order_id;

-- Match orders with shipment details
SELECT
    o.order_id,
    o.order_status,
    s.tracking_number,
    s.courier_name,
    s.shipment_status
FROM orders o
INNER JOIN shipments s
    ON o.order_id = s.order_id;

-- Display products and their reviews
SELECT
    p.product_id,
    p.product_name,
    r.rating,
    r.review_text
FROM products p
INNER JOIN reviews r
    ON p.product_id = r.product_id;

-- Display customer reviews with customer names
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    p.product_name,
    r.rating,
    r.review_text
FROM reviews r
INNER JOIN customers c
    ON r.customer_id = c.customer_id
INNER JOIN products p
    ON r.product_id = p.product_id;

-- Display order items with product details
SELECT
    oi.order_id,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_amount
FROM order_items oi
INNER JOIN products p
    ON oi.product_id = p.product_id;

-- Display complete order details with customer and product information
SELECT
    o.order_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_amount
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
INNER JOIN products p
    ON oi.product_id = p.product_id;

-- Calculate revenue by product category
SELECT
    c.category_name,
    SUM(oi.quantity * oi.unit_price - oi.discount_amount) AS total_revenue
FROM order_items oi
INNER JOIN products p
    ON oi.product_id = p.product_id
INNER JOIN categories c
    ON p.category_id = c.category_id
GROUP BY c.category_id, c.category_name
ORDER BY total_revenue DESC;

-- Calculate revenue generated by each seller
SELECT
    s.seller_name,
    SUM(oi.quantity * oi.unit_price - oi.discount_amount) AS total_revenue
FROM order_items oi
INNER JOIN products p
    ON oi.product_id = p.product_id
INNER JOIN sellers s
    ON p.seller_id = s.seller_id
GROUP BY s.seller_id, s.seller_name
ORDER BY total_revenue DESC;

-- Display customers who have never placed an order
SELECT
    c.customer_id,
    c.first_name,
    c.last_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Display products that have never been ordered
SELECT
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN order_items oi
    ON p.product_id = oi.product_id
WHERE oi.order_item_id IS NULL;

-- Display categories with their product counts
SELECT
    c.category_name,
    COUNT(p.product_id) AS total_products
FROM categories c
LEFT JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name;

-- Display customers with their total spending
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    COALESCE(SUM(o.total_amount), 0) AS total_spending
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spending DESC;

-- Display products with inventory information
SELECT
    p.product_id,
    p.product_name,
    p.stock_quantity,
    pi.quantity_available,
    pi.reorder_level
FROM products p
INNER JOIN product_inventory pi
    ON p.product_id = pi.product_id;

-- Display orders with payment and shipment information
SELECT
    o.order_id,
    o.order_status,
    o.total_amount,
    p.payment_method,
    p.payment_status,
    s.courier_name,
    s.shipment_status
FROM orders o
LEFT JOIN payments p
    ON o.order_id = p.order_id
LEFT JOIN shipments s
    ON o.order_id = s.order_id;

-- Compare each product with other products in the same category
SELECT
    p1.product_name AS product,
    p2.product_name AS related_product,
    p1.category_id
FROM products p1
INNER JOIN products p2
    ON p1.category_id = p2.category_id
    AND p1.product_id <> p2.product_id;

-- Create every possible customer and category combination
SELECT
    c.first_name,
    c.last_name,
    cat.category_name
FROM customers c
CROSS JOIN categories cat;

-- Join employees from the same department
SELECT
    e1.employee_id,
    CONCAT(e1.first_name, ' ', e1.last_name) AS employee_name,
    e1.department,
    e2.employee_id AS colleague_id,
    CONCAT(e2.first_name, ' ', e2.last_name) AS colleague_name
FROM employees e1
INNER JOIN employees e2
    ON e1.department = e2.department
    AND e1.employee_id <> e2.employee_id;