USE ecommerce_analytics;

-- Calculate customer spending using a common table expression
WITH customer_spending AS (
    SELECT
        customer_id,
        SUM(total_amount) AS total_spending
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    cs.total_spending
FROM customers c
INNER JOIN customer_spending cs
    ON c.customer_id = cs.customer_id
ORDER BY cs.total_spending DESC;

-- Find products priced above the average product price
WITH average_price AS (
    SELECT AVG(price) AS avg_price
    FROM products
)
SELECT
    product_id,
    product_name,
    price
FROM products
WHERE price > (SELECT avg_price FROM average_price);

-- Calculate revenue generated by each product
WITH product_revenue AS (
    SELECT
        product_id,
        SUM((quantity * unit_price) - discount_amount) AS revenue
    FROM order_items
    GROUP BY product_id
)
SELECT
    p.product_id,
    p.product_name,
    COALESCE(pr.revenue, 0) AS revenue
FROM products p
LEFT JOIN product_revenue pr
    ON p.product_id = pr.product_id
ORDER BY revenue DESC;

-- Calculate revenue generated by each category
WITH category_revenue AS (
    SELECT
        p.category_id,
        SUM((oi.quantity * oi.unit_price) - oi.discount_amount) AS revenue
    FROM order_items oi
    INNER JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY p.category_id
)
SELECT
    c.category_id,
    c.category_name,
    COALESCE(cr.revenue, 0) AS revenue
FROM categories c
LEFT JOIN category_revenue cr
    ON c.category_id = cr.category_id
ORDER BY revenue DESC;

-- Calculate total orders and spending for each customer
WITH customer_summary AS (
    SELECT
        customer_id,
        COUNT(*) AS total_orders,
        SUM(total_amount) AS total_spending,
        AVG(total_amount) AS average_order_value
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    cs.total_orders,
    cs.total_spending,
    ROUND(cs.average_order_value, 2) AS average_order_value
FROM customers c
INNER JOIN customer_summary cs
    ON c.customer_id = cs.customer_id
ORDER BY cs.total_spending DESC;

-- Find products with stock below the average stock level
WITH stock_summary AS (
    SELECT
        AVG(stock_quantity) AS average_stock
    FROM products
)
SELECT
    product_id,
    product_name,
    stock_quantity
FROM products
WHERE stock_quantity < (
    SELECT average_stock
    FROM stock_summary
);

-- Calculate monthly sales
WITH monthly_sales AS (
    SELECT
        YEAR(order_date) AS order_year,
        MONTH(order_date) AS order_month,
        SUM(total_amount) AS revenue
    FROM orders
    GROUP BY YEAR(order_date), MONTH(order_date)
)
SELECT
    order_year,
    order_month,
    revenue
FROM monthly_sales
ORDER BY order_year, order_month;

-- Find customers with more than one order
WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    co.total_orders
FROM customers c
INNER JOIN customer_orders co
    ON c.customer_id = co.customer_id
WHERE co.total_orders > 1;

-- Calculate product profit
WITH product_profit AS (
    SELECT
        product_id,
        price,
        cost_price,
        price - cost_price AS profit
    FROM products
)
SELECT
    product_id,
    price,
    cost_price,
    profit
FROM product_profit
ORDER BY profit DESC;

-- Find the highest revenue product
WITH product_revenue AS (
    SELECT
        product_id,
        SUM((quantity * unit_price) - discount_amount) AS revenue
    FROM order_items
    GROUP BY product_id
)
SELECT
    p.product_id,
    p.product_name,
    pr.revenue
FROM product_revenue pr
INNER JOIN products p
    ON pr.product_id = p.product_id
WHERE pr.revenue = (
    SELECT MAX(revenue)
    FROM product_revenue
);

-- Calculate seller performance
WITH seller_sales AS (
    SELECT
        p.seller_id,
        SUM((oi.quantity * oi.unit_price) - oi.discount_amount) AS revenue,
        SUM(oi.quantity) AS units_sold
    FROM order_items oi
    INNER JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY p.seller_id
)
SELECT
    s.seller_id,
    s.seller_name,
    COALESCE(ss.revenue, 0) AS revenue,
    COALESCE(ss.units_sold, 0) AS units_sold
FROM sellers s
LEFT JOIN seller_sales ss
    ON s.seller_id = ss.seller_id
ORDER BY revenue DESC;

-- Calculate average product rating
WITH product_ratings AS (
    SELECT
        product_id,
        AVG(rating) AS average_rating,
        COUNT(*) AS total_reviews
    FROM reviews
    GROUP BY product_id
)
SELECT
    p.product_id,
    p.product_name,
    ROUND(pr.average_rating, 2) AS average_rating,
    pr.total_reviews
FROM products p
INNER JOIN product_ratings pr
    ON p.product_id = pr.product_id
ORDER BY average_rating DESC;

-- Identify high-value customers
WITH customer_spending AS (
    SELECT
        customer_id,
        SUM(total_amount) AS total_spending
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    cs.total_spending
FROM customers c
INNER JOIN customer_spending cs
    ON c.customer_id = cs.customer_id
WHERE cs.total_spending >= 5000
ORDER BY cs.total_spending DESC;

-- Calculate inventory value for each product
WITH inventory_value AS (
    SELECT
        product_id,
        price * stock_quantity AS total_inventory_value
    FROM products
)
SELECT
    p.product_id,
    p.product_name,
    iv.total_inventory_value
FROM products p
INNER JOIN inventory_value iv
    ON p.product_id = iv.product_id
ORDER BY iv.total_inventory_value DESC;

-- Combine customer and order information using multiple CTEs
WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(*) AS total_orders,
        SUM(total_amount) AS total_spending
    FROM orders
    GROUP BY customer_id
),
customer_reviews AS (
    SELECT
        customer_id,
        COUNT(*) AS total_reviews
    FROM reviews
    GROUP BY customer_id
)
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    COALESCE(co.total_orders, 0) AS total_orders,
    COALESCE(co.total_spending, 0) AS total_spending,
    COALESCE(cr.total_reviews, 0) AS total_reviews
FROM customers c
LEFT JOIN customer_orders co
    ON c.customer_id = co.customer_id
LEFT JOIN customer_reviews cr
    ON c.customer_id = cr.customer_id
ORDER BY total_spending DESC;